import topics from '../src/topics.json';
interface Env{DB:D1Database;SITE_URL:string;GITHUB_OWNER_ID:string;GITHUB_CLIENT_ID:string;GITHUB_CLIENT_SECRET:string;LOCAL_ORIGIN?:string}
type User={id:string,username:string,provider:string,github_id:string|null,role:string,password_hash?:string,recovery_hash?:string};
const encoder=new TextEncoder(),topicIds=new Set(topics.map(t=>t.id));
const random=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');
const bytes=(s:string)=>new Uint8Array(s.match(/.{2}/g)!.map(h=>parseInt(h,16)));
const hex=(a:ArrayBuffer)=>Array.from(new Uint8Array(a),b=>b.toString(16).padStart(2,'0')).join('');
const hash=async(s:string)=>hex(await crypto.subtle.digest('SHA-256',encoder.encode(s)));
const challenge=async(s:string)=>btoa(String.fromCharCode(...new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(s))))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
function equal(a:string,b:string){let diff=a.length^b.length;for(let i=0;i<Math.max(a.length,b.length);i++)diff|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return diff===0}
async function passwordHash(password:string,salt=random()){const key=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveBits']);return `pbkdf2$100000$${salt}$${hex(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:bytes(salt),iterations:100000},key,256))}`}
async function verify(password:string,stored:string){const parts=stored.split('$');if(parts.length!==4)return false;return equal(await passwordHash(password,parts[2]),stored)}
function problem(message:string,status=400):never{throw Object.assign(new Error(message),{status})}
function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'}})}
function owner(u:User|null,e:Env){return !!u&&u.provider==='github'&&!!e.GITHUB_OWNER_ID&&u.github_id===e.GITHUB_OWNER_ID}
function session(u:User|null,e:Env){return {signedIn:!!u,name:u?.username||'',userId:u?.id,isOwner:owner(u,e),isAdmin:owner(u,e)||u?.role==='moderator'}}
async function identity(req:Request,e:Env){const auth=req.headers.get('authorization')||'';if(!/^Bearer [a-f0-9]{64}$/.test(auth))return null;return e.DB.prepare('SELECT u.* FROM users u JOIN sessions s ON s.user_id=u.id WHERE s.token_hash=? AND s.expires_at>?').bind(await hash(auth.slice(7)),Date.now()).first<User>()}
async function newSession(u:User,e:Env){const token=random();await e.DB.prepare('INSERT INTO sessions VALUES(?,?,?)').bind(await hash(token),u.id,Date.now()+(owner(u,e)?2:8)*3600000).run();return {token,session:session(u,e)}}
async function rate(e:Env,key:string,max:number,seconds:number){const now=Date.now(),bucket=Math.floor(now/(seconds*1000));const row=await e.DB.prepare('INSERT INTO rate_limits(key,n,expires_at) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET n=n+1 RETURNING n').bind(await hash(key+':'+bucket),now+seconds*2000).first<{n:number}>();if((row?.n||0)>max)problem('操作较频繁，请稍后再试。',429)}
async function body(req:Request){if(!(req.headers.get('content-type')||'').startsWith('application/json'))problem('需要 JSON 请求',415);const reader=req.body?.getReader();let total=0,s='';if(reader){const decoder=new TextDecoder();while(true){const {done,value}=await reader.read();if(done)break;total+=value.byteLength;if(total>16000){await reader.cancel();problem('请求内容过长',413)}s+=decoder.decode(value,{stream:true})}s+=decoder.decode()}try{return JSON.parse(s)}catch{problem('无效的请求内容')}}
function username(v:unknown){if(typeof v!=='string')problem('请填写用户名');const s=v.normalize('NFKC').trim();if(!/^[\p{L}\p{N}_]{3,24}$/u.test(s))problem('用户名需要 3–24 位字母、数字、中文或下划线');return {name:s,key:s.toLowerCase()}}
function validPassword(v:unknown):asserts v is string{if(typeof v!=='string'||v.length<12||v.length>128)problem('密码需要 12–128 个字符')}
function redirect(url:string,cookie?:string){return new Response(null,{status:302,headers:{Location:url,'Cache-Control':'no-store','Referrer-Policy':'no-referrer',...(cookie?{'Set-Cookie':cookie}:{})}})}
async function route(req:Request,e:Env){const url=new URL(req.url),path=url.pathname,method=req.method,ip=req.headers.get('cf-connecting-ip')||'local';
if(path==='/api/health')return json({ok:true,githubConfigured:!!e.GITHUB_CLIENT_ID&&!!e.GITHUB_CLIENT_SECRET});
if(path==='/api/auth/github'&&method==='GET'){
 if(!e.GITHUB_CLIENT_ID||!e.GITHUB_CLIENT_SECRET)problem('GitHub 登录尚未配置，请联系网站所有者。',503);
 const ch=url.searchParams.get('challenge')||'';if(!/^[A-Za-z0-9_-]{43}$/.test(ch))problem('登录校验信息不完整');await rate(e,'oauth:'+ip,20,60);const state=random(),verifier=random();await e.DB.prepare('INSERT INTO oauth_states VALUES(?,?,?,?)').bind(await hash(state),ch,verifier,Date.now()+600000).run();const next=new URL('https://github.com/login/oauth/authorize');next.search=new URLSearchParams({client_id:e.GITHUB_CLIENT_ID,redirect_uri:url.origin+'/api/auth/github/callback',state,scope:'',code_challenge:await challenge(verifier),code_challenge_method:'S256',allow_signup:'false'}).toString();return redirect(next.href,`__Host-acoustics-oauth=${state}; Secure; HttpOnly; SameSite=Lax; Path=/; Max-Age=600`)
}
if(path==='/api/auth/github/callback'&&method==='GET'){
 const clear='__Host-acoustics-oauth=; Secure; HttpOnly; SameSite=Lax; Path=/; Max-Age=0';try{const state=url.searchParams.get('state')||'',code=url.searchParams.get('code')||'',cookie=(req.headers.get('cookie')||'').split('; ').find(x=>x.startsWith('__Host-acoustics-oauth='))?.split('=')[1]||'';if(!state||!code||!equal(state,cookie))problem('登录验证失败',403);const st=await e.DB.prepare('DELETE FROM oauth_states WHERE state_hash=? AND expires_at>? RETURNING challenge,verifier').bind(await hash(state),Date.now()).first<{challenge:string,verifier:string}>();if(!st)problem('登录已过期');const tokenResponse=await fetch('https://github.com/login/oauth/access_token',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({client_id:e.GITHUB_CLIENT_ID,client_secret:e.GITHUB_CLIENT_SECRET,code,redirect_uri:url.origin+'/api/auth/github/callback',code_verifier:st.verifier})});const tokenData=await tokenResponse.json() as {access_token?:string};if(!tokenData.access_token)problem('GitHub 授权失败');const userResponse=await fetch('https://api.github.com/user',{headers:{Authorization:'Bearer '+tokenData.access_token,'User-Agent':'Acoustics-Lab',Accept:'application/vnd.github+json'}});const gu=await userResponse.json() as {id?:number,login?:string};if(!userResponse.ok||String(gu.id)!==e.GITHUB_OWNER_ID)problem('该 GitHub 账号不是网站所有者',403);const id='github:'+gu.id;await e.DB.prepare("INSERT INTO users(id,username,username_key,provider,github_id,role,created_at) VALUES(?,?,?,'github',?,'student',?) ON CONFLICT(id) DO UPDATE SET username=excluded.username").bind(id,gu.login,'github:'+gu.id,String(gu.id),Date.now()).run();const ticket=random();await e.DB.prepare('INSERT INTO login_tickets VALUES(?,?,?,?)').bind(await hash(ticket),id,st.challenge,Date.now()+60000).run();return redirect(e.SITE_URL+'#/callback?ticket='+ticket,clear)}catch{return redirect(e.SITE_URL+'#/callback?error=github',clear)}
}
const isPost=method==='POST';let data:any;if(isPost){data=await body(req);const origin=req.headers.get('origin');if(origin!==new URL(e.SITE_URL).origin&&!(e.LOCAL_ORIGIN&&url.hostname==='127.0.0.1'&&origin===e.LOCAL_ORIGIN))problem('请求来源不被允许',403)}
if(path==='/api/auth/exchange'&&isPost){if(typeof data.ticket!=='string'||typeof data.verifier!=='string'||!/^[a-f0-9]{64}$/.test(data.ticket)||!/^[a-f0-9]{64}$/.test(data.verifier))problem('无效的登录凭证');const ticket=await e.DB.prepare('DELETE FROM login_tickets WHERE ticket_hash=? AND challenge=? AND expires_at>? RETURNING user_id').bind(await hash(data.ticket),await challenge(data.verifier),Date.now()).first<{user_id:string}>();if(!ticket)problem('登录已失效，请重新登录',401);const u=await e.DB.prepare('SELECT * FROM users WHERE id=?').bind(ticket.user_id).first<User>();if(!u||!owner(u,e))problem('未获授权',403);return json(await newSession(u,e))}
if(['/api/auth/register','/api/auth/login','/api/auth/recover'].includes(path)&&isPost){
 await rate(e,'auth-ip:'+ip,20,60);const n=username(data.username);await rate(e,'auth-name:'+n.key,30,900);const password=data.password;if(typeof password!=='string'||password.length>128)problem('用户名或密码错误',401);
 const existing=await e.DB.prepare("SELECT * FROM users WHERE username_key=? AND provider='local'").bind(n.key).first<User>();
 if(path.endsWith('/register')){validPassword(password);await rate(e,'register:'+ip,10,3600);if(existing)problem('该用户名已被使用',409);const u:User={id:crypto.randomUUID(),username:n.name,provider:'local',github_id:null,role:'student'},recoveryCode=random();try{await e.DB.prepare("INSERT INTO users(id,username,username_key,password_hash,recovery_hash,provider,role,created_at) VALUES(?,?,?,?,?,'local','student',?)").bind(u.id,u.username,n.key,await passwordHash(password),await hash(recoveryCode),Date.now()).run()}catch{problem('用户名已被使用，请更换后重试',409)}return json({...await newSession(u,e),recoveryCode},201)}
 if(path.endsWith('/recover')){validPassword(password);if(!existing||typeof data.recovery!=='string'||!equal(await hash(data.recovery.trim()),existing.recovery_hash||''))problem('用户名或恢复码错误',401);const recoveryCode=random();const updated=await e.DB.prepare('UPDATE users SET password_hash=?,recovery_hash=? WHERE id=? AND recovery_hash=?').bind(await passwordHash(password),await hash(recoveryCode),existing.id,existing.recovery_hash).run();if(!updated.meta.changes)problem('恢复码已使用',409);await e.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(existing.id).run();return json({...await newSession(existing,e),recoveryCode})}
 const dummy='pbkdf2$100000$'+'0'.repeat(64)+'$'+'0'.repeat(64);if(!await verify(password,existing?.password_hash||dummy)||!existing)problem('用户名或密码错误',401);return json(await newSession(existing,e))
}
const u=await identity(req,e),s=session(u,e);
if(path==='/api/session'&&method==='GET')return json(s);
if(path==='/api/auth/logout'&&isPost){const token=(req.headers.get('authorization')||'').slice(7);await e.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await hash(token)).run();return json({ok:true})}
if(path==='/api/comments'&&method==='GET'){const topic=url.searchParams.get('topic')||'';if(!topicIds.has(topic))problem('知识点不存在');const published=await e.DB.prepare("SELECT id,nickname,body,created_at FROM comments WHERE topic=? AND status='approved' ORDER BY created_at DESC LIMIT 100").bind(topic).all();const mine=u?await e.DB.prepare("SELECT id,nickname,body,status,created_at FROM comments WHERE topic=? AND user_id=? AND status!='approved' ORDER BY created_at DESC LIMIT 30").bind(topic,u.id).all():{results:[]};return json({published:published.results,mine:mine.results})}
if(path==='/api/comments'&&isPost){if(!u)problem('请先登录',401);if(!topicIds.has(data.topic)||typeof data.body!=='string'||!data.body.trim()||data.body.length>2000||typeof data.id!=='string'||!/^[a-f0-9-]{36}$/.test(data.id))problem('请填写 1–2000 字的评论');const exists=await e.DB.prepare('SELECT user_id FROM comments WHERE id=?').bind(data.id).first<{user_id:string}>();if(exists){if(exists.user_id!==u.id)problem('提交标识冲突',409);return json({message:'该评论已收到，请勿重复提交。'})}await rate(e,'comment:'+u.id,5,60);await e.DB.prepare("INSERT INTO comments(id,topic,user_id,nickname,body,status,created_at) VALUES(?,?,?,?,?,'pending',?)").bind(data.id,data.topic,u.id,u.username,data.body.trim(),Date.now()).run();return json({status:'pending',message:'已提交，审核通过后公开。'},201)}
if(path==='/api/admin'){if(!u)problem('请先登录',401);if(!s.isAdmin)problem('没有审核权限',403);if(method==='GET'){const status=url.searchParams.get('status')||'pending';if(!['pending','approved','rejected'].includes(status))problem('无效状态');const rows=await e.DB.prepare('SELECT id,topic,nickname,body,status,created_at,reviewed_at FROM comments WHERE status=? ORDER BY created_at DESC LIMIT 200').bind(status).all();return json({comments:rows.results})}if(isPost){if(!['approved','rejected'].includes(data.status)||typeof data.id!=='string')problem('无效操作');const exists=await e.DB.prepare('SELECT id FROM comments WHERE id=?').bind(data.id).first();if(!exists)problem('评论不存在',404);await e.DB.batch([e.DB.prepare('UPDATE comments SET status=?,reviewed_at=?,reviewer=? WHERE id=?').bind(data.status,Date.now(),u.id,data.id),e.DB.prepare('INSERT INTO audit VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),u.id,'comment:'+data.status,data.id,Date.now())]);return json({ok:true})}}
if(path==='/api/members'){if(!owner(u,e))problem('只有网站所有者可管理管理员',403);if(method==='GET'){const rows=await e.DB.prepare("SELECT id,username,role FROM users WHERE provider='local' AND role='moderator' ORDER BY username").all();return json({members:rows.results})}if(isPost){const n=username(data.username);if(!['student','moderator'].includes(data.role))problem('不允许授予该权限');const target=await e.DB.prepare("SELECT id FROM users WHERE username_key=? AND provider='local'").bind(n.key).first<{id:string}>();if(!target)problem('该用户名尚未注册',404);await e.DB.batch([e.DB.prepare('UPDATE users SET role=? WHERE id=?').bind(data.role,target.id),e.DB.prepare('INSERT INTO audit VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),u!.id,'role:'+data.role,target.id,Date.now())]);return json({ok:true})}}
return json({error:'接口不存在'},404)
}
export default {async fetch(req:Request,e:Env,ctx:ExecutionContext){const origin=req.headers.get('origin'),allowed=origin===new URL(e.SITE_URL).origin||(!!e.LOCAL_ORIGIN&&new URL(req.url).hostname==='127.0.0.1'&&origin===e.LOCAL_ORIGIN);const cors:Record<string,string>=allowed?{'Access-Control-Allow-Origin':origin!,'Access-Control-Allow-Headers':'Content-Type,Authorization','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Vary':'Origin'}:{};if(req.method==='OPTIONS')return new Response(null,{status:allowed?204:403,headers:cors});let r:Response;try{r=await route(req,e)}catch(err){const x=err as Error&{status?:number};if(!x.status)console.error('API operation failed');r=json({error:x.status?x.message:'服务暂不可用，请稍后重试。'},x.status||503)}const response=new Response(r.body,r);for(const [k,v] of Object.entries(cors))response.headers.set(k,v);response.headers.set('X-Content-Type-Options','nosniff');if(Math.random()<.02)ctx.waitUntil(e.DB.batch(['sessions','oauth_states','login_tickets','rate_limits'].map(t=>e.DB.prepare(`DELETE FROM ${t} WHERE expires_at<?`).bind(Date.now()))));return response}};
