import assert from 'node:assert/strict';import {Miniflare} from 'miniflare';import {build} from 'esbuild';import fs from 'node:fs';import {webcrypto} from 'node:crypto';
fs.mkdirSync('outputs',{recursive:true});await build({entryPoints:['backend/worker.ts'],bundle:true,format:'esm',platform:'browser',outfile:'outputs/test-worker.mjs'});
const mf=new Miniflare({modules:true,scriptPath:'outputs/test-worker.mjs',compatibilityDate:'2026-05-15',d1Databases:['DB'],bindings:{SITE_URL:'https://shengyu-tang.github.io/acoustics-lab/',GITHUB_OWNER_ID:'155556685',GITHUB_CLIENT_ID:'',GITHUB_CLIENT_SECRET:''}});
const origin='https://shengyu-tang.github.io';const digest=async s=>Buffer.from(await webcrypto.subtle.digest('SHA-256',new TextEncoder().encode(s))).toString('hex');
async function req(path,data,token,expected=200,customOrigin=origin){const response=await mf.dispatchFetch('https://api.example.test'+path,{method:data?'POST':'GET',headers:{Origin:customOrigin,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(data?{body:JSON.stringify(data)}:{})});const result=await response.json();assert.equal(response.status,expected,JSON.stringify({path,result}));return result}
try{
const db=await mf.getD1Database('DB');for(const line of fs.readFileSync('backend/schema.sql','utf8').split(';').map(x=>x.trim()).filter(Boolean))await db.prepare(line).run();
const a=await req('/api/auth/register',{username:'测试学生A',password:'a safe test password 2026',role:'moderator',github_id:'155556685'},null,201);assert.equal(a.session.isAdmin,false);assert.equal(a.session.isOwner,false);
const b=await req('/api/auth/register',{username:'测试学生B',password:'another safe test password'},null,201);
await req('/api/auth/login',{username:'测试学生A',password:'wrong password'},null,401);await req('/api/auth/register',{username:'测试学生A',password:'valid duplicate password'},null,409);
const stored=await db.prepare('SELECT password_hash FROM users WHERE id=?').bind(a.session.userId).first();assert.ok(stored.password_hash.startsWith('pbkdf2$'));assert.ok(!stored.password_hash.includes('safe test password'));
const id=crypto.randomUUID();await req('/api/comments',{id,topic:'1.1.1',body:'<script>alert(1)</script> 测试评论',status:'approved',user_id:b.session.userId},a.token,201);
assert.equal((await req('/api/comments?topic=1.1.1')).published.length,0);assert.equal((await req('/api/comments?topic=1.1.1',null,b.token)).mine.length,0);assert.equal((await req('/api/comments?topic=1.1.1',null,a.token)).mine[0].status,'pending');
await req('/api/admin',null,a.token,403);await req('/api/members',{username:'测试学生B',role:'moderator'},a.token,403);await req('/api/comments',{id:crypto.randomUUID(),topic:'1.1.1',body:'CSRF'},a.token,403,'https://evil.example');
const ownerToken='a'.repeat(64);await db.prepare("INSERT INTO users(id,username,username_key,provider,github_id,role,created_at) VALUES('owner','Shengyu-Tang','github:155556685','github','155556685','student',?)").bind(Date.now()).run();await db.prepare('INSERT INTO sessions VALUES(?,?,?)').bind(await digest(ownerToken),'owner',Date.now()+600000).run();
assert.equal((await req('/api/session',null,ownerToken)).isOwner,true);await req('/api/members',{username:'测试学生B',role:'moderator'},ownerToken);assert.equal((await req('/api/session',null,b.token)).isAdmin,true);await req('/api/admin',{id,status:'approved'},b.token);const pub=(await req('/api/comments?topic=1.1.1')).published;assert.equal(pub.length,1);assert.equal(pub[0].user_id,undefined);
await req('/api/members',{username:'测试学生A',role:'moderator'},b.token,403);await req('/api/admin',{id,status:'rejected'},ownerToken);assert.equal((await req('/api/comments?topic=1.1.1')).published.length,0);await req('/api/members',{username:'测试学生B',role:'student'},ownerToken);await req('/api/admin',null,b.token,403);
const recovered=await req('/api/auth/recover',{username:'测试学生A',password:'new safe test password',recovery:a.recoveryCode});assert.ok(recovered.recoveryCode!==a.recoveryCode);assert.equal((await req('/api/session',null,a.token)).signedIn,false);await req('/api/auth/recover',{username:'测试学生A',password:'another safe password',recovery:a.recoveryCode},null,401);
await req('/api/auth/logout',{},recovered.token);assert.equal((await req('/api/session',null,recovered.token)).signedIn,false);
const ticket='b'.repeat(64),verifier='c'.repeat(64),ch=Buffer.from(await webcrypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))).toString('base64url');await db.prepare('INSERT INTO login_tickets VALUES(?,?,?,?)').bind(await digest(ticket),'owner',ch,Date.now()+60000).run();await req('/api/auth/exchange',{ticket,verifier:'d'.repeat(64)},null,401);const exchanged=await req('/api/auth/exchange',{ticket,verifier});assert.equal(exchanged.session.isOwner,true);await req('/api/auth/exchange',{ticket,verifier},null,401);
console.log('PASS: registration/login/recovery/logout, password hash, private pending comments, moderation, owner-only delegation, immediate revocation, Origin check, forged role/status rejected, one-time PKCE-bound ticket.');
}finally{await mf.dispose()}
