'use client';
import {useEffect,useState} from 'react';
import {api} from './api';
type Comment={id:string,nickname:string,body:string,status?:string,created_at:number};
export default function Comments({topic}:{topic:string}){const [session,setSession]=useState<{signedIn:boolean}|null>(null),[published,setPublished]=useState<Comment[]>([]),[mine,setMine]=useState<Comment[]>([]),[body,setBody]=useState(''),[nickname,setNickname]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[submission,setSubmission]=useState('');
 async function load(){setLoading(true);setError('');try{const [s,c]=await Promise.all([api('/api/session'),api('/api/comments?topic='+encodeURIComponent(topic))]);setSession(s);setNickname(s.name||'');setPublished(c.published);setMine(c.mine);}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[topic]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setNotice('');const id=submission||crypto.randomUUID();setSubmission(id);try{const d=await api('/api/comments',{method:'POST',body:JSON.stringify({id,topic,nickname,body})});setBody('');setSubmission('');setNotice(d.message||"已提交，等待审核");await load()}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
 return <section className="comments"><div className="discussion-heading"><h3>课程讨论 <small>· 审核后公开</small></h3><button className="secondary" onClick={load}>刷新</button></div><p className="muted">登录用于确认提交身份。公开内容只展示昵称、评论与时间；请勿在评论中填写学号、联系方式或其他个人信息。</p>{loading&&<p role="status">正在加载讨论…</p>}{error&&<p role="alert" className="error">{error}</p>}{session?.signedIn?<form onSubmit={submit}><label htmlFor="nickname">公开用户名</label><input id="nickname" readOnly required maxLength={30} value={nickname} onChange={e=>{setNickname(e.target.value);setSubmission('')}} placeholder="1–30 字"/><label htmlFor="comment">我的问题或观察</label><textarea id="comment" required maxLength={2000} value={body} onChange={e=>{setBody(e.target.value);setSubmission('')}} placeholder="例如：我把阻尼比调到 1 后，振子不再往复运动……"/><div className="form-bottom"><small>{body.length}/2000</small><button disabled={busy||!body.trim()||!nickname.trim()} className="primary">{busy?'正在提交…':'提交给管理员审核'}</button></div></form>:!loading&&!error&&<div className="signin-box"><p>阅读公开讨论无需登录。用本站用户名和密码登录即可参与讨论。</p><a target="_top" className="primary" href="#/account">注册 / 登录</a></div>}<p role="status">{notice}</p>{mine.length>0&&<div className="mine"><h3>我的提交 <small>仅自己可见</small></h3>{mine.map(c=><article key={c.id}><span className="tag">{c.status==='pending'?'待管理员审核':'未公开'}</span><p>{c.body}</p></article>)}</div>}<h3>已公开讨论 · {published.length}</h3>{!loading&&!error&&!published.length&&<div className="empty">这里还没有审核通过的评论。欢迎提出第一个问题。</div>}{published.map(c=><article className="comment" key={c.id}><div><strong>{c.nickname}</strong><time>{new Date(c.created_at).toLocaleString('zh-CN')}</time></div><p>{c.body}</p></article>)}</section>
}
