import {lazy,Suspense,useEffect,useState} from 'react';
import katex from 'katex';import Header from './Header';import {NumericInput} from './ui';import {fmt} from './physics';
import {comparisonCatalog,initial,layer,arrayFactor,gratingAngles,duct,ductModes,ductShape,type ComparisonKind,type Settings} from './comparisonPhysics';
const Scene=lazy(()=>import('./ComparisonScene'));
const parameters:Record<ComparisonKind,{key:string;label:string;min:number;max:number;step:number}[]>={
 layer:[{key:'q',label:'层阻抗比 Z₂/Z₁',min:.2,max:20,step:.1},{key:'s',label:'出口阻抗比 Z₃/Z₁',min:.2,max:20,step:.1},{key:'h',label:'层厚 / 波长 d/λ₂',min:0,max:1,step:.005}],
 array:[{key:'N',label:'阵元数 N',min:2,max:16,step:1},{key:'d',label:'阵元间距 / 波长 d/λ',min:.1,max:2,step:.05},{key:'steer',label:'扫描角 θ₀（°）',min:-60,max:60,step:1}],
 duct:[{key:'a',label:'管半径 a（m）',min:.05,max:.5,step:.01},{key:'f',label:'频率 f（Hz）',min:50,max:4000,step:10},{key:'z',label:'观察截面距离 z（m）',min:0,max:2,step:.05}]
};
const copy:Record<ComparisonKind,{intro:string;question:string;answer:string;formula:string[];limit:string}>={
 layer:{intro:'超声探头要把声能送入被测介质，保护层却可能把能量反射回来。设计一层被动匹配材料：比较直接接触与增加有限厚度层时的透射，再考察厚度偏差带来的性能变化。',question:'同一种材料，为什么四分之一波长与半波长的透射效果不同？',answer:'层内的往返相位随厚度改变。四分之一波长时，若 Z₂²=Z₁Z₃，可抵消入口反射；半波长时等效回到两外侧介质直接相接。匹配通常只在设计频率附近有效。',formula:[String.raw`T=\frac{4Z_1Z_3}{(Z_1+Z_3)^2\cos^2\delta+(Z_2+Z_1Z_3/Z_2)^2\sin^2\delta},\quad\delta=2\pi d/\lambda_2`,String.raw`R+T=1,\qquad d=\lambda_2/4,\quad Z_2=\sqrt{Z_1Z_3}\Rightarrow T=1`],limit:'无损流体等效层、法向入射、无限平面，忽略剪切波。动画为方便比较令三介质声速相同，通过密度改变阻抗。R、T 是功率系数。'},
 array:{intro:'水下机器人希望只听清目标方向，却不能无限增加换能器。用均匀线阵比较阵元数量和间距：更窄的主瓣能否同时避免把其他方向误判为目标？',question:'为什么增大阵元间距可能出现与主瓣一样高的峰？',answer:'当另一方向也使相邻阵元相位差为 2π 的整数倍时，各阵元再次同相叠加，形成栅瓣。半波长以内的间距可在通常扫描范围内避免栅瓣，但普通旁瓣仍存在。',formula:[String.raw`D(\theta)=\left|\frac1N\sum_{j=0}^{N-1}e^{\,i2\pi(j-(N-1)/2)(d/\lambda)(\sin\theta-\sin\theta_0)}\right|`,String.raw`\sin\theta_g=\sin\theta_0+m\lambda/d,\quad m\in\mathbb Z\setminus\{0\},\quad |\sin\theta_g|\le1`],limit:'等幅点阵元、理想相位控制、远场，无互耦和单元指向性。角度相对阵列正侧向；三维曲面绕线阵轴具有对称性，二维扫描角不能区分全部三维方位。'},
 duct:{intro:'通风圆管或声学测量管中，频率升高后声压不再在截面上均匀分布。选择不同模态，比较节径、节圆与截止频率，判断一个截面测点能否代表整个声场。',question:'横截面上存在振型，是否就意味着声能可以沿管道传播？',answer:'不一定。频率低于该模态截止频率时，轴向响应指数衰减。只有高于截止频率才有传播模态；无损模型在截止处轴向波数与群速度均为零。平面模态无正截止频率。',formula:[String.raw`\tilde p_{nm}=A J_n(\beta_{nm}r/a)\cos(n\varphi)e^{-ik_z z},\quad J_n'(\beta_{nm})=0`,String.raw`f_c=\frac{c\beta_{nm}}{2\pi a},\quad k_z^2=(2\pi f/c)^2-(\beta_{nm}/a)^2,\quad f<f_c:\ |p(z)|\propto e^{-\kappa z}`],limit:'刚性圆管、均匀空气 c=340 m/s、无流动和热黏损耗，单一模态。横截面以共同模态系数 A=1 比较，轴向曲线以入口振幅为 1。节径模态还存在旋转等价解。'}
};
function readKind():ComparisonKind{const id=new URLSearchParams(location.hash.split('?')[1]).get('experiment');return comparisonCatalog.find(x=>x.id===id)?.id||'layer';}
export function ComparisonLinks({models}:{models:string[]}){const entries=comparisonCatalog.filter(x=>x.models.some(m=>models.includes(m)));return entries.length?<aside className="comparison-links"><strong>进一步比较</strong>{entries.map(x=><a key={x.id} href={'#/compare?experiment='+x.id}>{x.title} ↗</a>)}</aside>:null;}
function metrics(kind:ComparisonKind,v:Settings):[string,string][]{if(kind==='layer'){const a=layer(v);return [['功率透射率 T',fmt(a.T*100)+'%'],['功率反射率 R',fmt(a.R<1e-14?0:a.R*100)+'%'],['透射损失',fmt(-10*Math.log10(a.T))+' dB']];}if(kind==='array'){const g=gratingAngles(v);return [['孔径 / 波长',fmt((v.N-1)*v.d)],['扫描方向响应',fmt(Math.hypot(...arrayFactor(Math.sin(v.steer*Math.PI/180),v)))],['额外栅瓣角度',g.length?g.map(a=>fmt(a)+'°').join('、'):'无']];}const d=duct(v);return [['截止频率',fmt(d.fc)+' Hz'],['轴向状态',d.state],['1 m 处相对幅度',fmt(Math.exp(-d.decay))],['群速度',fmt(d.cg)+' m/s']];}
function curve(kind:ComparisonKind,v:Settings){return Array.from({length:401},(_,i)=>{const q=i/400;if(kind==='layer')return layer({...v,h:q}).T;if(kind==='array')return Math.hypot(...arrayFactor(Math.sin((-90+180*q)*Math.PI/180),v));return Math.exp(-duct(v).decay*q*2);});}
function path(a:number[]){return a.map((y,i)=>`${i?'L':'M'}${50+i*520/(a.length-1)},${220-y*175}`).join(' ');}
export default function Comparisons(){const [kind,setKind]=useState<ComparisonKind>(readKind),[v,setV]=useState<Settings>(()=>({...initial[readKind()]})),[saved,setSaved]=useState<Settings|null>(null),[show,setShow]=useState(false),[status,setStatus]=useState('');
 const choose=(next:ComparisonKind)=>{setKind(next);setV({...initial[next]});setSaved(null);setShow(false);setStatus('');};useEffect(()=>{const fn=()=>choose(readKind());window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn)},[]);
 const entry=comparisonCatalog.find(x=>x.id===kind)!,text=copy[kind],rows=metrics(kind,v),prior=saved?metrics(kind,saved):null;
 function download(){const body={experiment:entry.title,current:v,saved,results:rows,savedResults:prior,assumptions:text.limit};const u=URL.createObjectURL(new Blob([JSON.stringify(body,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='声学对照-'+kind+'.json';a.click();URL.revokeObjectURL(u);}
 return <><Header/><main className="comparison-page"><div className="eyebrow">COMPARE / 用对照发现规律</div><h1>让两组方案，同台比较。</h1><p className="lead">先预测，再保存一组参数；改变条件，用曲线和声场检验你的判断。</p><nav className="comparison-switch" aria-label="选择对照实验">{comparisonCatalog.map(x=><a key={x.id} aria-current={x.id===kind?'page':undefined} href={'#/compare?experiment='+x.id}>{x.title}</a>)}</nav><section className="paper"><h2>{entry.title}</h2><p>{text.intro}</p><div className="comparison-actions"><button className="primary" onClick={()=>{setSaved({...v});setStatus('当前参数已保存为方案 A，继续调整方案 B。')}}>保存为方案 A</button><button className="secondary" onClick={()=>{if(saved)setV({...saved});}} disabled={!saved}>恢复方案 A</button><button className="secondary" onClick={()=>choose(kind)}>重置全部</button><button className="secondary" onClick={download}>导出对照记录</button></div><p role="status">{status}</p>
 <div className="comparison-workbench"><Suspense fallback={<p>正在载入三维对照场景…</p>}><Scene key={kind} kind={kind} v={v}/></Suspense><div className="comparison-controls"><h3>方案 B · 当前参数</h3>{kind==='duct'&&<label>圆管模态<select aria-label="圆管模态" value={v.mode} onChange={e=>setV(a=>({...a,mode:Number(e.target.value)}))}>{ductModes.map((m,i)=><option value={i} key={m.name}>{m.name}</option>)}</select></label>}{parameters[kind].map(p=><label key={p.key}>{p.label}<div><input aria-label={p.label} type="range" min={p.min} max={p.max} step={p.step} value={v[p.key]} onChange={e=>setV(a=>({...a,[p.key]:Number(e.target.value)}))}/><NumericInput id={'compare-'+p.key} aria-label={p.label+'数值'} min={p.min} max={p.max} step={p.step} value={v[p.key]} onValueChange={n=>setV(a=>({...a,[p.key]:n}))}/></div></label>)}{kind==='layer'&&<button className="secondary" onClick={()=>setV({...v,q:4,s:16,h:.25})}>四分之一波匹配示例</button>}{kind==='array'&&<button className="secondary" onClick={()=>setV({...v,d:1.5,steer:0})}>观察栅瓣：间距 1.5λ</button>}{kind==='duct'&&<p>当前频率 / 截止频率：{duct(v).fc?fmt(v.f/duct(v).fc):'平面模态无截止'}</p>}</div></div>
 <div className="comparison-table-wrap"><table className="comparison-table"><caption>定量对照</caption><thead><tr><th>指标</th><th>方案 A · 已保存</th><th>方案 B · 当前</th></tr></thead><tbody>{rows.map(([name,value],i)=><tr key={name}><th>{name}</th><td>{prior?.[i][1]||'尚未保存'}</td><td>{value}</td></tr>)}</tbody></table></div>
 <div className="comparison-plots"><figure><figcaption>{kind==='layer'?'厚度扫描 · 功率透射率':kind==='array'?'角度扫描 · 归一化声压幅度':'轴向包络 · 相对入口振幅'}</figcaption><svg viewBox="0 0 620 285" role="img" aria-label="方案 A 与方案 B 的对照曲线"><path d="M50 35V220H570" className="comparison-axis"/>{saved&&<path d={path(curve(kind,saved))} className="comparison-saved"/>}<path d={path(curve(kind,v))} className="comparison-current"/>{kind==='layer'&&saved&&<circle cx={50+520*saved.h} cy={220-layer(saved).T*175} r="7" fill="none" stroke="#cd9048" strokeWidth="2"/>}{kind==='layer'&&<circle cx={50+520*v.h} cy={220-layer(v).T*175} r="5" fill="#d29743"/>}<text x="18" y="49">1</text><text x="18" y="224">0</text><text x="50" y="250">{kind==='array'?'−90°':'0'}</text><text x="512" y="250">{kind==='array'?'90°':kind==='layer'?'1.0 d/λ₂':'2.0 m'}</text></svg><p><span className="comparison-key-a">— 方案 A</span>　<span className="comparison-key-b">— 方案 B</span></p><small>{kind==='layer'?'实心点为当前厚度，空心圈为方案 A 厚度。厚度扫描曲线相同并不代表工作点相同，请同时比较透射率。':kind==='duct'?'传播时无损包络为常数；截止以下随 z 指数衰减。曲线只表示包络，不表示瞬时声压。':'正侧向为 0°。主瓣之外的普通旁瓣仍可能存在，栅瓣特指与主瓣同高的相干峰。'}</small></figure>
 <div className="comparison-question"><h3>{text.question}</h3><button className="secondary" onClick={()=>setShow(!show)}>{show?'收起分析':'查看分析'}</button>{show&&<p>{text.answer}</p>}{saved&&<details><summary>展开方案 A 参数</summary>{Object.entries(saved).map(([key,value])=><p key={key}>{parameters[kind].find(p=>p.key===key)?.label||'圆管模态'}：{key==='mode'?ductModes[value].name:fmt(value)}</p>)}</details>}{kind==='duct'&&<div className="duct-mini"><strong>当前截面径向剖面（φ=0）</strong><svg viewBox="0 0 300 150" role="img" aria-label="圆管径向模态函数"><path d="M20 70H280M20 10V130" className="comparison-axis"/><path d={Array.from({length:101},(_,i)=>`${i?'L':'M'}${20+2.6*i},${70-55*ductShape(i/100,0,v)}`).join(' ')} className="comparison-current"/><text x="20" y="146">中心</text><text x="250" y="146">管壁</text></svg></div>}</div></div>
 <h3>用公式解释对照结果</h3><div className="equation-block">{text.formula.map((f,i)=><div className="equation-row" key={f}><div className="equation-math" dangerouslySetInnerHTML={{__html:katex.renderToString(f,{displayMode:true,throwOnError:true,trust:false})}}/><span>({i+1})</span></div>)}</div><p>{text.limit}</p><a className="secondary" href={'#/lab?topic='+entry.topic}>回到对应课程知识点 ↗</a></section><footer><a href="mailto:tangshengyu@ouc.edu.cn">建议反馈：tangshengyu@ouc.edu.cn</a></footer></main></>;
}
