import {useEffect,useRef,useState} from 'react';
import {atlasEntries as topics} from './courseCatalog';import {names,colors,chapterStories} from './atlas';
const W=1940;
const groups=names.slice(1).map((name,i)=>({name,chapter:i+1,topics:topics.filter(t=>t.chapter===i+1)}));
let leftY=130;const layout=groups.map(g=>{const right=g.chapter===3,start=right?110:leftY,height=g.topics.length*46;if(!right)leftY+=height+90;return {...g,right,start,y:start+height/2}});
const H=Math.max(2520,...layout.map(g=>g.start+g.topics.length*46+100));
export default function CourseTree(){const area=useRef<HTMLDivElement>(null),drag=useRef<{x:number,y:number,left:number,top:number}|null>(null);const [scale,setScale]=useState(.5),[selected,setSelected]=useState(0),[query,setQuery]=useState('');
useEffect(()=>{const el=area.current!;setScale(Math.min(el.clientWidth/W,el.clientHeight/H))},[]);
function zoom(next:number){const el=area.current!;next=Math.max(.15,Math.min(1.6,next));const x=(el.scrollLeft+el.clientWidth/2)/scale,y=(el.scrollTop+el.clientHeight/2)/scale;setScale(next);requestAnimationFrame(()=>{el.scrollLeft=x*next-el.clientWidth/2;el.scrollTop=y*next-el.clientHeight/2})}
function focus(chapter:number){const g=layout.find(g=>g.chapter===chapter)!;setSelected(chapter);setScale(.8);requestAnimationFrame(()=>area.current!.scrollTo({left:(g.right?1050:0)*.8,top:Math.max(0,g.start*.8-30),behavior:'smooth'}))}
return <section className="course-tree"><div className="tree-toolbar"><input aria-label="搜索思维导图" placeholder="搜索知识点…" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={()=>zoom(scale*1.25)} aria-label="放大思维导图">＋</button><button onClick={()=>zoom(scale/1.25)} aria-label="缩小思维导图">−</button><button onClick={()=>{setScale(Math.min(area.current!.clientWidth/W,area.current!.clientHeight/H));area.current!.scrollTo(0,0)}}>全景</button><button onClick={()=>zoom(1)}>清晰阅读</button></div>{query&&<div className="tree-search-results">{topics.filter(t=>(t.id+t.title).includes(query)).map(t=><a key={t.id} href={t.href}>{t.isProject?'项目':t.id} {t.title} ↗</a>)}</div>}<div className="chapter-shortcuts">{groups.map(g=><button key={g.chapter} onClick={()=>focus(g.chapter)}>{g.name}</button>)}</div><div className="tree-viewport" ref={area} tabIndex={0} aria-label="全部展开的课程思维导图，可滚动浏览" onPointerDown={e=>{if(e.pointerType!=='mouse'||(e.target as Element).closest('a,button'))return;drag.current={x:e.clientX,y:e.clientY,left:e.currentTarget.scrollLeft,top:e.currentTarget.scrollTop};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{const d=drag.current;if(d){e.currentTarget.scrollLeft=d.left-e.clientX+d.x;e.currentTarget.scrollTop=d.top-e.clientY+d.y}}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>
<svg width={W*scale} height={H*scale} viewBox={`0 0 ${W} ${H}`} aria-label="声学基础完整课程体系"><rect width={W} height={H} fill="#f4f9fa"/><g><rect x="825" y={H/2-50} width="260" height="100" rx="30" fill="#123c4c"/><text x="955" y={H/2-6} textAnchor="middle" fill="white" fontSize="30">声学基础</text><text x="955" y={H/2+25} textAnchor="middle" fill="#94d8d5" fontSize="17">振动 · 传播 · 声源 · 接收</text></g>{layout.map(g=>{const cx=g.right?1195:710,tx=g.right?1390:25,color=colors[g.chapter-1];return <g key={g.chapter}><path d={`M ${g.right?1085:825} ${H/2} C ${cx} ${H/2} ${955} ${g.y} ${cx} ${g.y}`} fill="none" stroke={color} strokeWidth="5"/>{g.topics.map((t,i)=>{const y=g.start+i*46;return <g key={t.id} opacity={query&&!(t.id+t.title).includes(query)?.25:1}><path d={`M ${cx} ${g.y} C ${cx} ${y+18} ${g.right?1320:590} ${y+18} ${g.right?tx:tx+520} ${y+18}`} fill="none" stroke={color} strokeWidth="2"/><a href={t.href}><rect x={tx} y={y} width="520" height="38" rx="10" fill="white" stroke={color}/><text x={tx+13} y={y+25} fill="#214655" fontSize="17">{t.isProject?'项目':t.id} · {t.title}</text><title>{t.focus||t.title}</title></a></g>})}<g onClick={()=>setSelected(g.chapter)}><rect x={cx-110} y={g.y-29} width="220" height="58" rx="17" fill="#153d4c" stroke={color} strokeWidth="3"/><text x={cx} y={g.y+7} textAnchor="middle" fill="white" fontSize="22">{g.name}</text></g></g>})}</svg></div><p className="tree-hint">拖动或滚动浏览 · 用“全景”看完整体系，用章节按钮定位 · 点击知识点进入实验</p>{selected>0&&<aside className="paper"><h3>{names[selected]} · 学习脉络</h3><p>{chapterStories[selected]}</p></aside>}<a className="primary" href="#/cases">把知识串起来：跨领域综合案例 ↗</a></section>}
