import {useEffect,useRef,useState} from 'react';import * as T from 'three';import {OrbitControls} from 'three/addons/controls/OrbitControls.js';import {lensPattern,type LensSettings} from './lensPhysics';
export default function LensScene({v}:{v:LensSettings}){const host=useRef<HTMLDivElement>(null),current=useRef(v),playing=useRef(true),[paused,setPaused]=useState(false),[failed,setFailed]=useState(false),reset=useRef(()=>{});current.current=v;playing.current=!paused;
useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)setPaused(true)},[]);
useEffect(()=>{const el=host.current!;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true})}catch{setFailed(true);return}renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0x081e2c);el.appendChild(renderer.domElement);renderer.domElement.setAttribute('role','img');renderer.domElement.setAttribute('aria-label','梯度透镜与连续远场波束三维示意');let fitScale=1;const scene=new T.Scene(),camera=new T.PerspectiveCamera(42,1,.1,100);camera.position.set(10,5,12);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(2.5,0,0);controls.enableDamping=true;controls.minDistance=6;controls.maxDistance=28;reset.current=()=>{camera.position.set(10,5,12).multiplyScalar(fitScale);controls.target.set(2.5,0,0)};scene.add(new T.HemisphereLight(0xc6fbff,0x214250,3));const light=new T.DirectionalLight(0xffffff,3);light.position.set(-2,5,5);scene.add(light);
const material=(color:number,opacity=1)=>new T.MeshStandardMaterial({color,roughness:.35,metalness:.15,transparent:opacity<1,opacity,depthWrite:opacity===1,side:T.DoubleSide});const source=new T.Mesh(new T.CylinderGeometry(.4,.4,.6,32),material(0x7bdccf));source.rotation.z=Math.PI/2;source.position.x=-1.3;scene.add(source);const dome=new T.Mesh(new T.SphereGeometry(1.35,48,24,0,Math.PI*2,0,Math.PI/2),material(0x80b8d0,.13));dome.rotation.z=-Math.PI/2;dome.position.x=-1;scene.add(dome);
const rings=Array.from({length:24},(_,i)=>{const ring=new T.Mesh(new T.RingGeometry(i/24*1.3,(i+1)/24*1.3,64),material(0x69cbbf,.8));ring.rotation.y=Math.PI/2;ring.position.x=.4;scene.add(ring);return ring});
const pixels=new Uint8Array(361*4),texture=new T.DataTexture(pixels,361,1,T.RGBAFormat);texture.minFilter=texture.magFilter=T.LinearFilter;texture.needsUpdate=true;const uniforms={pattern:{value:texture},time:{value:0},frequency:{value:30}};const fieldMat=new T.ShaderMaterial({uniforms,transparent:true,depthWrite:false,side:T.DoubleSide,blending:T.AdditiveBlending,vertexShader:`varying vec3 p;void main(){p=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec3 p;uniform sampler2D pattern;uniform float time,frequency;void main(){float x=p.x-.4;float r=length(p.yz);float angle=atan(r,max(.03,x));vec4 sampleValue=texture2D(pattern,vec2(.5+angle/3.14159265,.5));float a=sampleValue.r*2.-1.,b=sampleValue.g*2.-1.;float distance=sqrt(x*x+r*r);float phase=frequency/30.*(distance*6.-time*4.);float pressure=a*cos(phase)-b*sin(phase);float edge=smoothstep(0.,.5,x)*(1.-smoothstep(6.5,7.5,x))*(1.-smoothstep(1.8,2.5,abs(p.y)));float opacity=.16*(1.-exp(-2.*abs(pressure)))*edge;gl_FragColor=vec4(pressure>=0.?vec3(.28,.92,.84):vec3(1.,.59,.35),opacity);}`});for(let i=0;i<11;i++){const geom=new T.PlaneGeometry(7.5,5);geom.translate(4.15,0,(i/10-.5)*3.8);scene.add(new T.Mesh(geom,fieldMat))}
const grid=new T.GridHelper(16,32,0x315164,0x234251);grid.position.set(2,-2.6,0);grid.material.transparent=true;grid.material.opacity=.25;scene.add(grid);let stamp='',time=0,last=0,raf=0,visible=true;const io=new IntersectionObserver(([e])=>visible=e.isIntersecting);io.observe(el);const ro=new ResizeObserver(()=>{renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix()});ro.observe(el);
const loop=(now:number)=>{const dt=last?Math.min(.04,(now-last)/1000):0;last=now;if(visible&&!document.hidden){if(playing.current)time+=dt;const next=current.current,tag=JSON.stringify(next);if(tag!==stamp){const s=lensPattern(next);for(let i=0;i<361;i++){pixels[i*4]=Math.round((s.real[i]+1)*127.5);pixels[i*4+1]=Math.round((s.imag[i]+1)*127.5);pixels[i*4+2]=0;pixels[i*4+3]=255}texture.needsUpdate=true;rings.forEach((r,i)=>{r.visible=i<next.rings;r.geometry.dispose();r.geometry=new T.RingGeometry(i/next.rings*1.3,(i+1)/next.rings*1.3,64);r.material.color.setHSL(.48+i/next.rings*.14,.52,.4);r.material.opacity=next.correction===0?.08:.7});uniforms.frequency.value=next.frequency;stamp=tag}uniforms.time.value=time;controls.update();renderer.render(scene,camera)}raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(raf);ro.disconnect();io.disconnect();controls.dispose();texture.dispose();scene.traverse(o=>{const m=o as T.Mesh;m.geometry?.dispose();if(m.material)(Array.isArray(m.material)?m.material:[m.material]).forEach(x=>x.dispose())});renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove()};},[]);
return <div className="lens-scene"><div className="lens-scene-tools"><span>环带透镜 → 波前校正 → 远场波束</span><button onClick={()=>setPaused(!paused)}>{paused?'播放透镜动画':'暂停透镜动画'}</button><button onClick={()=>reset.current()}>复位透镜视角</button></div><div className="lens-scene-host" ref={host}/>{failed&&<p>此设备未启用三维显示，仍可使用方向图与相位曲线。</p>}<p>拖动旋转 · 滚轮缩放。青／暖色表示正／负声压；三维场景呈现计算所得的远场方向性，尺寸与传播时间作示意缩放。</p></div>}
