export type Values=Record<string,number>;
export type Param={key:string,label:string,unit:string,min:number,max:number,step:number,value:number};
export type Model={title:string,formula:string,meaning:string,limit:string,question:string,answer:string,application:string,task:string,params:Param[],preset:Values,view:string};
const p=(key:string,label:string,unit:string,min:number,max:number,step:number,value:number):Param=>({key,label,unit,min,max,step,value});
const vib=[p('m','质量 m','kg',0.2,5,0.1,1),p('k','刚度 K','N/m',20,500,10,100),p('z','阻尼比 ζ','',0,2,0.02,0.1)];
const wave=[p('f','频率 f','Hz',100,3000,50,500),p('c','声速 c','m/s',300,1800,10,1500),p('rho','密度 ρ₀','kg/m³',1.2,1200,0.1,1000),p('P','声压峰值 P','Pa',0.1,10,0.1,1)];
export const models:Record<string,Model>={
 free:{title:'自由振动',formula:'mẍ + Kx = 0;  ω₀ = √(K/m);  x = A cos(ω₀t)',meaning:'m 是质量，K 是刚度；初始位移 A = 1 cm，初始速度为零。质量增大使振动变慢。',limit:'线性弹簧、单自由度、无阻尼；位移以实际值计算，动画位移放大。',question:'质量变为原来的四倍，固有频率变为多少？',answer:'变为一半，因为 f₀ 与质量平方根成反比。',application:'仪器支架的固有频率',task:'保持刚度不变，比较 1 kg 与 4 kg 仪器的固有频率。判断是否接近 2 Hz 的环境激励。',params:vib.slice(0,2),preset:{m:4,k:100},view:'oscillator'},
 energy:{title:'振动与能量交换',formula:'E = ½mẋ² + ½Kx² = ½KA²',meaning:'动能与弹性势能周期性交换；经过平衡位置时动能最大。A = 1 cm。',limit:'无阻尼、无外力的线性单自由度系统。',question:'振子在最大位移处速度是多少？',answer:'速度为零，此时能量全部为弹性势能。',application:'弹性储能机构',task:'把刚度加倍，观察同样初始位移下总能量和振动速度如何变化。',params:vib.slice(0,2),preset:{m:2,k:200},view:'oscillator'},
 damp:{title:'阻尼与衰减',formula:'mẍ + Rₘẋ + Kx = 0;  ζ = Rₘ/(2√(Km));  δ = ζω₀',meaning:'ζ < 1 为欠阻尼；ζ = 1 为临界阻尼；ζ > 1 为过阻尼。使用 x(0)=1 cm、ẋ(0)=0 的完整解。',limit:'黏性线性阻尼；过阻尼不是振幅较小的简谐振动。',question:'阻尼比大于 1 时还会往复振动吗？',answer:'不会。两个实指数分量使系统非周期地回到平衡位置。',application:'仪表指针的稳定时间',task:'将阻尼比依次改为 0.1、1、1.8，比较超调与返回速度。',params:vib,preset:{m:1,k:100,z:1},view:'oscillator'},
 quality:{title:'品质因数与脉冲拖尾',formula:'Q = 1/(2ζ);  τₐ = 1/(ζω₀);  Δω = 2ζω₀',meaning:'τₐ 是振幅包络下降到 1/e 的时间；Q 越大，振动拖尾越长。带宽为速度响应的半功率带宽。',limit:'欠阻尼线性系统；振幅时间常数与教材中其他“过渡时间”定义不可混用。',question:'高 Q 换能器是否适合无限短的脉冲？',answer:'高 Q 意味着窄带和长拖尾，会限制短脉冲的时间分辨能力。',application:'声呐发射换能器的拖尾',task:'将阻尼比从 0.05 改到 0.3，比较 Q 与振幅时间常数。',params:[...vib.slice(0,2),p('z','阻尼比 ζ','',0.02,0.8,0.01,0.05)],preset:{z:0.3},view:'oscillator'},
 forced:{title:'强迫振动与过渡过程',formula:'mẍ + Rₘẋ + Kx = F₀ cos(ωt);  x = x暂态 + x稳态',meaning:'外力峰值 F₀ = 1 N，系统由静止起振；显示数值积分的完整响应。改变频率比可看到共振和起振过程。',limit:'线性黏性阻尼模型；曲线以 RK4 积分，稳态幅值另用解析式计算。',question:'稳态振动频率由谁决定？',answer:'由外力频率决定；暂态部分包含系统自由响应。',application:'换能器的启动响应',task:'将激励频率比设为 1，再增大阻尼，比较启动超调与稳态振幅。',params:[...vib,p('ratio','激励频率比 ω/ω₀','',0.2,2,0.02,0.8)],preset:{ratio:1,z:0.15},view:'forced'},
 resonance:{title:'机械阻抗与共振',formula:'Zₘ = Rₘ + j(ωm − K/ω);  X = F₀ / √[(K−mω²)²+(Rₘω)²]',meaning:'X 为位移幅值；速度共振在 ω₀，位移共振在 ω₀√(1−2ζ²)，后者仅在 ζ < 1/√2 时存在。F₀=1 N。',limit:'稳态、线性、恒幅谐和力；图中 X 按静位移 F₀/K 归一化。',question:'速度共振频率与位移共振频率总相等吗？',answer:'不总相等。有阻尼时位移峰值频率较低；阻尼足够大时位移幅频曲线没有非零频率峰。',application:'机械设备避开共振区',task:'把工作频率比从 0.5 调到 1，再调到 1.8，比较响应放大倍数。',params:[...vib.slice(0,2),p('z','阻尼比 ζ','',0.02,1.5,0.02,0.1),p('ratio','工作频率比 ω/ω₀','',0.1,3,0.02,1)],preset:{ratio:1.8,z:0.2},view:'resonance'},
 beats:{title:'拍与相干叠加',formula:'cos(2πf₁t)+cos(2πf₂t) = 2cos[π(f₁−f₂)t]cos[π(f₁+f₂)t]',meaning:'合成信号的强弱周期由拍频 |f₁−f₂| 决定；图示等幅信号。',limit:'线性叠加；动画载频作慢放，数值仍使用实际频率。',question:'440 Hz 与 442 Hz 叠加，拍频是多少？',answer:'2 Hz，不是平均频率 441 Hz。',application:'乐器调音',task:'把第二个频率从 446 Hz 逐渐调向 440 Hz，观察包络变化。',params:[p('f1','第一频率 f₁','Hz',430,450,0.5,440),p('f2','第二频率 f₂','Hz',430,450,0.5,442)],preset:{f1:440,f2:446},view:'beats'},
 string:{title:'弦的横振动与简正模态',formula:'∂²y/∂t² = (T/μ)∂²y/∂x²;  c = √(T/μ);  fₙ = nc/(2L)',meaning:'两端固定：y(0)=y(L)=0；振型 sin(nπx/L)。T 为张力，μ 为线密度。拨弦点在某阶节点处时，该阶不易激发。',limit:'均匀柔弦、小斜率、恒张力；振型为单一模态，动画位移归一化。',question:'第 3 阶模态含两端共有几个节点？',answer:'4 个节点。张力加倍则固有频率变为 √2 倍。',application:'琴弦的音高与泛音',task:'保持弦长与线密度不变，改变张力，比较前三阶模态。',params:[p('T','张力 T','N',10,200,5,80),p('mu','线密度 μ','kg/m',0.001,0.02,0.001,0.005),p('L','弦长 L','m',0.2,2,0.05,0.8),p('n','模态阶数 n','',1,6,1,1)],preset:{T:120,n:3},view:'string'},
 rod:{title:'细棒纵振动',formula:'c = √(E/ρ);  fₙ = (2n−1)c/(4L)',meaning:'本实验为一端固定、一端自由的均匀细棒。固定端位移为零，自由端轴向应力为零。',limit:'细长棒、一维纵振动；不是无限固体中的体纵波公式。E 输入单位为 GPa。',question:'固定—自由棒的基频是 c/(2L) 还是 c/(4L)？',answer:'c/(4L)，长度等于基模的四分之一波长。',application:'纵振式超声杆',task:'改变杆长与材料弹性模量，估计将基频移到超声频段所需的长度。',params:[p('E','杨氏模量 E','GPa',10,220,5,200),p('rho','密度 ρ','kg/m³',1000,9000,100,7800),p('L','杆长 L','m',0.02,1,0.01,0.5),p('n','模态阶数 n','',1,5,1,1)],preset:{L:0.06,E:200},view:'rod'},
 wave:{title:'声学基本量与传播',formula:'p = P cos(ωt−kx);  u = p/(ρ₀c);  λ = c/f;  k = 2π/λ',meaning:'声速是波形传播速度；质点振速是介质局部往复运动的速度。P 是峰值而不是有效值。',limit:'均匀、无耗散理想流体中的线性平面行波；粒子位移放大展示，粒子不会随波整体迁移。',question:'质点振速变大，声速就一定变大吗？',answer:'不会。线性模型中声速由介质性质决定，振速幅值由声压与特性阻抗决定。',application:'水下通信的波长设计',task:'比较相同频率在空气和水中的波长，观察波前与介质质点的不同运动。',params:wave,preset:{c:340,rho:1.2,f:1000},view:'wave'},
 continuity:{title:'连续性、状态与运动方程',formula:'∂ρ′/∂t + ρ₀∇·u = 0;  p = c²ρ′;  ρ₀∂u/∂t = −∇p',meaning:'依次表达质量守恒、线性状态关系和牛顿第二定律。消去 ρ′ 与 u 得到 ∇²p − c⁻²∂²p/∂t² = 0。',limit:'小扰动 |ρ′|≪ρ₀、无黏、均匀静止介质；图中密度扰动由 p/c² 同步计算。',question:'密度扰动 ρ′ 和总密度 ρ₀+ρ′ 是同一个量吗？',answer:'不是。线性方程描述相对平衡态的小扰动。',application:'声传感器中的压力—密度换算',task:'固定声压峰值，提高声速，观察密度扰动幅值如何减小。',params:wave,preset:{c:340,rho:1.2,P:2},view:'wave'},
 speed:{title:'介质压缩性与声速',formula:'c = √(B/ρ₀);  λ = c/f',meaning:'B 为绝热体积弹性模量；越难压缩，通常声速越高，但也受密度影响。',limit:'均匀流体、小振幅、绝热过程；不能仅凭密度比较两种介质声速。',question:'B 增大四倍，密度不变，声速怎样变化？',answer:'声速增大到两倍。',application:'水与空气的传播差异',task:'将体积模量设为 2.25 GPa、密度设为 1000 kg/m³，得到水中约 1500 m/s 的声速。',params:[p('B','体积弹性模量 B','GPa',0.01,4,0.01,2.25),p('rho','密度 ρ₀','kg/m³',100,1500,10,1000),p('f','频率 f','Hz',100,2000,100,500)],preset:{B:2.25,rho:1000},view:'wave'},
 intensity:{title:'声能、声强与声阻抗',formula:'e = p²/(2ρ₀c²) + ρ₀u²/2;  I = ⟨pu⟩ = P²/(2ρ₀c)',meaning:'e 是瞬时声能密度，pu 是瞬时能流密度，I 是时间平均声强。P 为声压峰值。',limit:'I=P²/(2ρ₀c) 仅适用于无损平面行波；驻波中不可直接套用。',question:'声压峰值增加到两倍，平面行波声强增加多少？',answer:'四倍。若给定的是有效值，则 I=pᵣₘₛ²/(ρ₀c)，不再除以 2。',application:'水听器信号换算为声强',task:'比较同样声压峰值在不同介质中的振速与声强。',params:wave,preset:{P:2,c:1500,rho:1000},view:'wave'},
 levels:{title:'声压级与声级叠加',formula:'Lₚ = 20log₁₀(pᵣₘₛ/pᵣₑf);  LΣ = 10log₁₀(10^(L₁/10)+10^(L₂/10))',meaning:'空气参考声压 20 μPa，水中 1 μPa。这里两声源不相干，叠加的是均方声压。',limit:'两级必须采用同一参考值；声压级不等同于 A 计权级；该实验不判定法规合规。',question:'两个相同的 60 dB 不相干声源叠加是多少？',answer:'约 63.01 dB。等幅同相的相干声源才增加约 6.02 dB。',application:'机房两台设备的噪声叠加',task:'将第二台设备从 60 dB 降到 40 dB，观察总声级的降低幅度。',params:[p('L1','声源 1','dB',20,120,1,60),p('L2','声源 2','dB',20,120,1,60),p('ref','参考声压','μPa',1,20,19,20)],preset:{L1:60,L2:40},view:'levels'},
 interference:{title:'相干干涉与相位',formula:'PΣ = √(P₁²+P₂²+2P₁P₂cosφ)',meaning:'同频、稳定相位差的波按声压叠加；本实验 P₁=1 Pa，P₂ 可调。',limit:'理想单点相干叠加；反相抵消不代表整个空间都安静。',question:'等幅声波在相位差 180° 时会怎样？',answer:'在这个观测点完全抵消；换一个位置相位差可能改变。',application:'主动降噪的相位误差',task:'把相位设为 180°，再偏离 20°，观察残余声压。',params:[p('P2','第二声压峰值','Pa',0,2,0.05,1),p('phase','相位差 φ','°',0,360,5,180)],preset:{P2:1,phase:160},view:'interference'},
 doppler:{title:'多普勒效应',formula:'f接收 = f源 c/(c−vₛ)',meaning:'声源沿声源—接收器连线运动，接收器相对介质静止；vₛ>0 表示靠近。',limit:'均匀静止介质、亚声速声源；不适用于激波。',question:'声源靠近时接收频率升高还是降低？',answer:'升高，因为相邻波前被压缩。',application:'移动声源的音调变化',task:'把声源速度由 −60 m/s 调到 +60 m/s，比较前方波前间距。',params:[p('f','发射频率','Hz',100,2000,50,500),p('v','声源速度 vₛ','m/s',-100,100,5,30)],preset:{v:60},view:'doppler'},
 reflection:{title:'边界条件与垂直入射',formula:'pᵢ+pᵣ=pₜ;  uᵢ+uᵣ=uₜ;  r=(Z₂−Z₁)/(Z₂+Z₁);  t=1+r',meaning:'Z=ρc；声强反射率 R=r²，透射率 T=4Z₁Z₂/(Z₁+Z₂)²。反射波的振速相对声压变号。',limit:'平面界面、两侧无耗散流体、垂直入射；声压透射系数可大于 1，不违反能量守恒。',question:'声压透射系数大于 1 是否意味着能量增加？',answer:'不是。计算声强需同时考虑介质阻抗，仍有 R+T=1。',application:'空气—水界面的声阻抗失配',task:'令阻抗比 Z₂/Z₁=100，观察反射率；再调到 1 比较匹配情况。',params:[p('q','阻抗比 Z₂/Z₁','',0.01,100,0.01,4)],preset:{q:100},view:'reflection'},
 oblique:{title:'斜入射、折射与全内反射',formula:'sinθᵢ/c₁ = sinθₜ/c₂;  r=(Z₂cosθᵢ−Z₁cosθₜ)/(Z₂cosθᵢ+Z₁cosθₜ)',meaning:'角度均相对界面法线。c₂>c₁ 时存在临界角 arcsin(c₁/c₂)；超过临界角透射侧为倏逝场。',limit:'无损流体平面界面；全内反射仍有近界面声场，不向法向远处输送平均能量。',question:'全内反射时另一侧是否完全没有声场？',answer:'仍存在沿法向指数衰减的倏逝场。',application:'海底界面的临界掠射条件',task:'设速度比 1.5，逐渐增加入射角，找出临界角并检查法向能流守恒。',params:[p('ratio','声速比 c₂/c₁','',0.5,2,0.05,1.5),p('q','阻抗比 Z₂/Z₁','',0.2,5,0.1,2),p('angle','入射角 θᵢ','°',0,85,1,30)],preset:{ratio:1.5,angle:60},view:'oblique'},
 standing:{title:'阻抗表面与驻波',formula:'r=(zₛ−1)/(zₛ+1);  SWR=(1+|r|)/(1−|r|);  α=1−|r|²',meaning:'zₛ 是表面法向阻抗除以 ρc 的归一化复数；本实验可调电阻性部分和电抗性部分。',limit:'局部作用、不透射的终端表面、法向入射；α 指吸收率，区别于介质吸收系数。',question:'吸收最好时是阻抗最大，还是阻抗匹配？',answer:'阻抗匹配 zₛ=1+0j 最佳，此时反射为零。',application:'阻抗管评价吸声层',task:'保持实部为 1，将虚部从 0 调到 3，观察吸声率和驻波比。',params:[p('R','归一化阻抗实部','',0.05,5,0.05,1),p('X','归一化阻抗虚部','',-5,5,0.1,1)],preset:{R:1,X:0},view:'standing'},
 spherical:{title:'球面波与几何扩展',formula:'p(r) ∝ e^(−jkr)/r;  I(r) ∝ 1/r²;  TL = 20log₁₀(r/r₀)',meaning:'在三维均匀空间，声功率通过越来越大的球面；归一化声阻抗 z=(kr)²/[1+(kr)²]+jkr/[1+(kr)²]。',limit:'向外传播的均匀球面波，采用 e^(jωt)；r₀=1 m。无吸收，非零距离。',question:'距离加倍，球面扩展损失增加多少？',answer:'约 6.02 dB；声强变为四分之一。',application:'水下点声源的距离损失',task:'把接收距离从 10 m 增大到 20 m，检查声压与声强的变化。',params:[p('r','接收距离 r','m',1,100,1,10),p('f','频率 f','Hz',50,2000,50,500)],preset:{r:20},view:'spherical'},
 image:{title:'镜像声源与水面反射',formula:'p ∝ e^(−jkr₁)/r₁ ± e^(−jkr₂)/r₂',meaning:'软边界用反相镜像，硬边界用同相镜像；r₁、r₂ 是直达与镜像路径长度。声速 1500 m/s，接收深度 10 m。',limit:'无限平面、理想软或硬边界、点声源；忽略吸收和海底。',question:'理想软边界上，直达声与反射声怎样叠加？',answer:'等程且反相，声压为零。',application:'浅水直达声与水面反射的干涉',task:'改变声源深度或频率，观察 100 m 处接收幅值的起伏。',params:[p('depth','声源深度','m',1,30,1,5),p('f','频率','Hz',100,2000,50,500),p('sign','边界：−1 软，+1 硬','',-1,1,2,-1)],preset:{depth:15,f:1000},view:'image'},
 cylindrical:{title:'柱面波与传播损失',formula:'p ∝ H₀⁽²⁾(kr);  |p|远场 ∝ r^(−½);  TL远场 = 10log₁₀(r/r₀)',meaning:'远场圆柱面面积随半径线性增长，因此声强与距离成反比。',limit:'无限长线源、kr≫1 的远场近似；曲线从 r₀=10 m 起算，c=1500 m/s、f=1 kHz。',question:'柱面远场距离加倍，声级下降多少？',answer:'约 3.01 dB，区别于球面扩展的 6.02 dB。',application:'浅海传播的柱面扩展近似',task:'比较 100 m 与 200 m 的相对扩展损失。该模型不含海底损耗。',params:[p('r','距离 r','m',10,1000,10,100)],preset:{r:200},view:'cylindrical'},
 guide:{title:'平行平面层波导',formula:'kₓ²=(2πf/c)²−(nπ/H)²;  f꜀=nc/(2H);  cₚ=fλₓ;  cɡ=c²/cₚ',meaning:'本实验两壁绝对硬，横向振型 cos(nπz/H)，n=0 为无截止的平面模态。c=1500 m/s。',limit:'均匀无损硬—硬波导；不能直接把这个截止式用于软—硬海洋波导。截止以下沿轴衰减。',question:'硬—硬波导的 n=0 模态有正截止频率吗？',answer:'没有，f꜀=0。高阶模态须高于各自截止频率才传播。',application:'浅海声信道的模态筛选',task:'设 H=20 m、n=2，改变频率跨过 75 Hz，比较传播与倏逝。',params:[p('H','波导厚度 H','m',5,100,5,20),p('n','横向阶数 n','',0,5,1,2),p('f','频率 f','Hz',10,500,5,100)],preset:{H:20,n:2,f:50},view:'guide'},
 monopole:{title:'脉动球源与辐射阻抗',formula:'zᵣ = (ka)²/[1+(ka)²] + jka/[1+(ka)²];  W=½·4πa²ρc·Re(zᵣ)·U²',meaning:'a 是球半径，U 为表面振速峰值；ρ=1000 kg/m³、c=1500 m/s。小 ka 时辐射效率低。',limit:'均匀脉动球、无限理想流体；点声源近似需要 ka≪1 且观测距离远大于声源尺度。',question:'低频换能器为什么常需要较大的尺寸？',answer:'固定表面振速下，提高 ka 可提高归一化辐射阻，改善辐射能力。',application:'低频水声发射器尺寸选择',task:'保持振速不变，比较 0.05 m 与 0.2 m 半径球源在 500 Hz 的辐射功率。',params:[p('a','球半径 a','m',0.01,0.5,0.01,0.1),p('f','频率 f','Hz',50,5000,50,500),p('U','表面振速峰值 U','m/s',0.001,0.05,0.001,0.01)],preset:{a:0.2,f:500},view:'monopole'},
 dipole:{title:'声偶极子与指向性',formula:'D(θ)=cosθ;  p远场 ∝ jkd cosθ · e^(−jkr)/r',meaning:'两个等强反相点声源组成偶极子，沿轴辐射强，垂直轴线方向相消。',limit:'kd≪1、kr≫1 的远场偶极近似；图示归一化幅值，声速 1500 m/s。',question:'偶极子在垂直于轴线方向的声压怎样？',answer:'理想偶极子在该方向为零。',application:'开放式扬声器的声短路',task:'改变声源间距与频率，观察 kd；比较轴向与侧向的辐射幅值。',params:[p('d','两源间距 d','m',0.001,0.05,0.001,0.02),p('f','频率 f','Hz',50,1000,50,500),p('angle','观察角 θ','°',0,180,5,30)],preset:{angle:90},view:'dipole'},
 piston:{title:'圆形活塞与瑞利积分',formula:'D(θ)=2J₁(ka sinθ)/(ka sinθ);  p ∝ ∫ₛ U e^(−jkr)/r dS',meaning:'大障板上均匀圆活塞的各微元按相位叠加，形成主瓣和旁瓣；D(0)=1。',limit:'无限刚性障板、匀速活塞、远场指向性；只显示前半空间。c=1500 m/s。',question:'提高 ka，主瓣通常变宽还是变窄？',answer:'变窄，方向选择性更强；可能出现旁瓣。',application:'声呐换能器的波束设计',task:'保持半径 0.1 m，将频率从 5 kHz 调到 15 kHz，比较 30° 方向响应。',params:[p('a','活塞半径 a','m',0.01,0.3,0.01,0.1),p('f','频率 f','Hz',500,15000,500,5000),p('angle','观察角 θ','°',0,90,1,30)],preset:{a:0.1,f:15000},view:'piston'},
 nearfield:{title:'活塞轴向声场与远近场',formula:'|p(z)|/(ρcU)=2|sin{(k/2)[√(z²+a²)−z]}|;  N≈a²/λ',meaning:'轴上各面元传播路程不同，近场出现起伏；N 为常用瑞利距离估计，不能当作严格分界。',limit:'无限障板均匀圆活塞轴向解；c=1500 m/s，U 为表面振速峰值。',question:'测量远场指向性应把接收器放在哪里？',answer:'应使距离远大于声源尺度及相关瑞利距离，并验证远场条件。',application:'水池指向性测量的测距选择',task:'提高频率或活塞尺寸，观察瑞利距离增长与轴向干涉起伏。',params:[p('a','活塞半径','m',0.02,0.3,0.01,0.1),p('f','频率','Hz',1000,30000,500,10000),p('r','轴上距离','m',0.01,3,0.01,0.5)],preset:{a:0.2,f:20000,r:0.5},view:'nearfield'},
 scatter:{title:'刚性球的瑞利散射',formula:'σₛ ≈ (7π/9)a²(ka)⁴;  pₛ远场 ∝ (ka)³(½cosθ−⅓)/(kr)',meaning:'长波条件下总散射截面正比于频率四次方、半径六次方。σₛ 是等效面积。',limit:'刚性球、ka≤0.3 的低频近似、远场；不能用于鱼鳔共振或任意形状目标。c=1500 m/s。',question:'频率加倍且仍在瑞利区，散射截面增加多少？',answer:'16 倍；半径加倍则增大 64 倍。',application:'小目标回波的频率选择',task:'保持半径 1 cm，将频率从 1 kHz 增到 2 kHz，比较散射截面。',params:[p('a','刚性球半径','m',0.001,0.02,0.001,0.01),p('f','频率','Hz',100,3000,100,1000)],preset:{f:2000,a:0.01},view:'scatter'},
 cylinder:{title:'绝对软圆柱的散射',formula:'pᵢ+pₛ=0 (r=a);  Aₙ=−iⁿJₙ(ka)/Hₙ⁽²⁾(ka)',meaning:'软边界使表面总声压为零；动画显示圆柱面上入射与散射声压逐点抵消。级数系数给出外部场的求解方法。',limit:'无限长、绝对软圆柱；动画只求解边界声压，不将边界图误作完整外部散射场。',question:'软圆柱边界上的散射声压是否为零？',answer:'一般不为零，它恰好抵消入射声压，使总声压为零。',application:'低阻抗圆柱目标的边界响应',task:'改变 ka，观察圆柱表面声压相位分布；实际气泡或弹性壳体还需更复杂边界。',params:[p('ka','无量纲半径 ka','',0.1,8,0.1,2)],preset:{ka:5},view:'cylinder'},
 receiver:{title:'声接收与频率响应',formula:'U电 = M(f)p;  |H| = 1/√[(1−r²)²+(2ζr)²]',meaning:'采用二阶低通接收链路模型，r=f/f₀；非平坦幅频响应会改变不同频率分量比例。M₀ 为低频灵敏度。',limit:'教学用线性接收链路，不替代真实水听器的校准曲线；P=1 Pa。',question:'只在一个频率灵敏度很高，就一定能忠实接收宽带信号吗？',answer:'不能。宽带接收还需平坦幅频响应和适当相频响应。',application:'水听器测量链路的频响',task:'改变阻尼比，比较接近谐振处的放大与高频衰减。',params:[p('ratio','频率比 f/f₀','',0.1,3,0.05,0.5),p('z','阻尼比','',0.1,1.5,0.05,0.7),p('M','低频灵敏度 M₀','mV/Pa',1,100,1,10)],preset:{ratio:1,z:0.2},view:'receiver'},
 reciprocity:{title:'声场互易原理',formula:'pB/QA = pA/QB;  G(A,B)=G(B,A)',meaning:'相同体积速度源在 A、B 互换，传播格林函数保持相同；声压幅值随距离变化。',limit:'线性、静止、互易介质和互易边界，收发类型与归一化相同；流动介质和主动非互易器件不保证成立。',question:'互易原理是否要求两个点收到的声压在任意源强下都相等？',answer:'不是。应比较对源体积速度归一化后的传递函数。',application:'水听器互易校准的传播部分',task:'改变 A、B 间距，再交换收发位置，观察两方向归一化传递幅值相同。',params:[p('r','A、B 间距','m',1,50,1,10),p('f','频率','Hz',100,3000,100,1000)],preset:{r:20},view:'reciprocity'},
 absorption:{title:'介质吸收与复波数',formula:'p(x)=p₀e^(−αx);  I(x)=I₀e^(−2αx);  TL吸收=8.686αx',meaning:'α 为声压幅值吸收系数，单位 Np/m；同一 α 下声强指数里有因子 2。',limit:'均匀平面传播、无几何扩展；图中 α 与距离均以米为基准。',question:'声压降为 1/e 时，声强降为多少？',answer:'降为 1/e²，约 13.5%。',application:'水下通信链路的吸收损失',task:'设置 α=0.001 Np/m，对比 100 m 与 500 m 的额外损失。',params:[p('alpha','幅值吸收系数 α','Np/m',0,0.01,0.0001,0.001),p('r','传播距离','m',10,1000,10,100)],preset:{alpha:0.001,r:500},view:'absorption'},
 mechanism:{title:'吸收机理与频率',formula:'α经典 = C f²;  α弛豫 = A f²/(fᵣ²+f²)',meaning:'黏滞和热传导引起耗散；弛豫使不同频段的吸收规律发生变化。这里比较归一化频率的两种项。',limit:'展示机理模型而非海水经验预报；r=f/fᵣ，α=α₀[r²+βr²/(1+r²)]，α₀=0.001 Np/m。',question:'所有频段的海水吸收都可简单写为 C f² 吗？',answer:'不可以。不同弛豫过程和介质状态会改变频率依赖关系。',application:'通信频率与吸收代价',task:'提高相对频率，比较 100 m 传播中经典项和弛豫项带来的声压衰减。',params:[p('ratio','相对频率 f/fᵣ','',0.1,5,0.1,1),p('beta','弛豫项相对强度 β','',0,5,0.1,1)],preset:{ratio:3},view:'mechanism'},
 sonar:{title:'主动声呐综合案例',formula:'SE=SL−2TL+TS−NL+DI−DT;  TL=20log₁₀r+αdB·r/1000',meaning:'r 以 m 输入，αdB 单位 dB/km。SE≥0 仅表示在这个噪声受限简化模型下满足阈值。',limit:'单基地、球面扩展、固定目标强度、噪声受限；不含混响、海洋声速剖面或检测概率。SL 采用水中 1 μPa、1 m 参考。',question:'主动声呐为何有 2TL？',answer:'声波经历发射器到目标以及目标到接收器的往返传播损失。',application:'探测距离与系统参数取舍',task:'提高声源级 6 dB，比较在吸收存在时作用距离是否恰好翻倍。固定 TS=10、NL=60、DI=10、DT=10 dB。',params:[p('r','目标距离','m',100,20000,100,1000),p('SL','声源级 SL','dB',180,230,1,210),p('alpha','吸收系数','dB/km',0,10,0.1,1)],preset:{r:5000,SL:216},view:'sonar'}
};
models.undamped={...models.forced,title:'无阻尼强迫振动',formula:'mẍ+Kx=F₀cosωt; x=F₀(cosωt−cosω₀t)/[m(ω₀²−ω²)]',meaning:'由静止起振，ω≠ω₀ 时出现两频率叠加；ω=ω₀ 时极限解为 F₀t sin(ω₀t)/(2mω₀)，振幅持续增长。',limit:'无阻尼理想模型，无限增长最终会使线性小振幅假设失效；不应声称存在有限共振稳态。',question:'无阻尼系统在固有频率处受持续谐和激励，能达到有限幅值稳态吗？',answer:'不能。共振解的包络随时间线性增长，实际系统会受阻尼或非线性限制。',params:models.forced.params.filter(p=>p.key!=='z'),preset:{m:1,k:100,ratio:1},application:'理想换能器的持续共振激励',task:'把频率比从 0.8 调到 1，比较拍动和共振增长。实际设计必须计入阻尼。'};
models.echo={title:'回音壁的沿壁传播',formula:'ℓ弧=Rθ;  ℓ弦=2R sin(θ/2);  Δt=(ℓ弧−ℓ弦)/c',meaning:'声线以较小掠射角沿曲面多次反射，可把能量约束在壁附近。以圆弧路径作为几何近似，与直达弦路径比较到达时间。θ 使用弧度。',limit:'高频几何声学路径示意；不是精确回音壁波场，也不把流体界面全内反射当作唯一成因。c=340 m/s。',question:'相同两点之间，沿壁路径一定比直达路径更短吗？',answer:'不会。圆弧长不小于弦长；沿壁声可以因几何约束而更容易被接收。',application:'圆形展厅的沿壁回声',task:'改变厅堂半径和听者角位置，比较沿壁与直达路径的时间差。',params:[p('R','圆形墙半径','m',5,50,1,15),p('angle','听者方位角','°',10,180,5,120)],preset:{R:25,angle:180},view:'echo'};
models.helmholtz={title:'亥姆霍兹方程与波矢',formula:'∇²p̃+k²p̃=0;  p̃=P e^(−j k⃗·r⃗);  kₓ²+kᵧ²=k²',meaning:'令 p=Re[p̃ e^(jωt)] 后，波动方程转为亥姆霍兹方程。波矢垂直等相位面，改变方向只改变分量而不改变波数模。',limit:'二维显示三维平面波的截面；均匀无损介质，c=1500 m/s。',question:'改变传播方向，波数的模一定改变吗？',answer:'在同一均匀介质和相同频率下不变，只是 kₓ 与 kᵧ 分量改变。',application:'平面阵列接收的相位梯度',task:'旋转传播方向，观察二维波前与沿阵列方向的相位变化。',params:[p('f','频率','Hz',100,2000,100,500),p('angle','波矢方向','°',0,180,5,30)],preset:{f:1000,angle:60},view:'helmholtz'};
export function defaults(m:Model):Values{return {z:0,...Object.fromEntries(m.params.map(p=>[p.key,p.value]))};}
export function j1(x:number){let term=x/2,sum=term; for(let n=1;n<90;n++){term*=-(x*x/4)/(n*(n+1));sum+=term;if(Math.abs(term)<1e-14)break;}return sum;}
export function pistonD(x:number){return Math.abs(x)<1e-6?1:2*j1(x)/x;}
export function freeX(v:Values,t:number,damped=true){const w=Math.sqrt(v.k/v.m),z=damped?(v.z??0):0; if(z===1)return .01*Math.exp(-w*t)*(1+w*t); if(z<1){const d=w*Math.sqrt(1-z*z);return .01*Math.exp(-z*w*t)*(Math.cos(d*t)+z*w/d*Math.sin(d*t));}const a=-w*(z-Math.sqrt(z*z-1)),b=-w*(z+Math.sqrt(z*z-1));return .01*(b*Math.exp(a*t)-a*Math.exp(b*t))/(b-a);}
export function reflection(q:number){const r=(q-1)/(q+1);return {r,t:1+r,R:r*r,T:4*q/(q+1)**2};}
export function oblique(v:Values){const a=v.angle*Math.PI/180,s=v.ratio*Math.sin(a),ci=Math.cos(a);if(s>=1)return {R:1,T:0,angle:NaN,critical:Math.asin(1/v.ratio)*180/Math.PI};const ct=Math.sqrt(1-s*s),r=(v.q*ci-ct)/(v.q*ci+ct);return {R:r*r,T:4*v.q*ci*ct/(v.q*ci+ct)**2,angle:Math.asin(s)*180/Math.PI,critical:v.ratio>1?Math.asin(1/v.ratio)*180/Math.PI:NaN};}
export function result(kind:string,v:Values):[string,number,string][]{const w=Math.sqrt(v.k/v.m),f0=w/(2*Math.PI),ka=2*Math.PI*v.f*(v.a??v.d)/1500; switch(kind){
case 'undamped':return [['固有频率',f0,'Hz'],['激励频率',f0*v.ratio,'Hz']];
case 'echo':{const arc=v.R*v.angle*Math.PI/180,chord=2*v.R*Math.sin(v.angle*Math.PI/360);return [['沿壁路径',arc,'m'],['直达路径',chord,'m'],['到达时间差',(arc-chord)/340*1000,'ms']];}
case 'helmholtz':{const k=2*Math.PI*v.f/1500;return [['波数 k',k,'rad/m'],['波数分量 kₓ',k*Math.cos(v.angle*Math.PI/180),'rad/m'],['波数分量 kᵧ',k*Math.sin(v.angle*Math.PI/180),'rad/m']];}
case 'free':case 'energy':return [['固有频率',f0,'Hz'],['初始总能量',.5*v.k*.01**2,'J']];
case 'damp':case 'quality':return [['固有频率',f0,'Hz'],['阻尼系数 δ',v.z*w,'s⁻¹'],['品质因数 Q',1/(2*v.z),''],['包络时间常数',1/(v.z*w),'s']];
case 'forced':case 'resonance':return [['固有频率',f0,'Hz'],['稳态位移幅值',1000/(v.k*Math.hypot(1-v.ratio**2,2*v.z*v.ratio)),'mm'],['速度共振频率',f0,'Hz']];
case 'beats':return [['拍频',Math.abs(v.f1-v.f2),'Hz'],['平均频率',(v.f1+v.f2)/2,'Hz']];
case 'string':return [['波速',Math.sqrt(v.T/v.mu),'m/s'],['简正频率',v.n*Math.sqrt(v.T/v.mu)/(2*v.L),'Hz']];
case 'rod':return [['纵波速度',Math.sqrt(v.E*1e9/v.rho),'m/s'],['简正频率',(2*v.n-1)*Math.sqrt(v.E*1e9/v.rho)/(4*v.L),'Hz']];
case 'wave':case 'continuity':case 'intensity':return [['波长',v.c/v.f,'m'],['振速峰值',v.P/(v.rho*v.c),'m/s'],['平均声强',v.P*v.P/(2*v.rho*v.c),'W/m²'],['密度扰动峰值',v.P/(v.c*v.c),'kg/m³']];
case 'speed':return [['声速',Math.sqrt(v.B*1e9/v.rho),'m/s'],['波长',Math.sqrt(v.B*1e9/v.rho)/v.f,'m']];
case 'levels':{const L=10*Math.log10(10**(v.L1/10)+10**(v.L2/10));return [['合成声压级',L,'dB'],['合成有效声压',v.ref*1e-6*10**(L/20),'Pa']];}
case 'interference':return [['合成声压峰值',Math.sqrt(Math.max(0,1+v.P2**2+2*v.P2*Math.cos(v.phase*Math.PI/180))),'Pa']];
case 'doppler':return [['接收频率',v.f*340/(340-v.v),'Hz'],['前方波长',(340-v.v)/v.f,'m']];
case 'reflection':{const a=reflection(v.q);return [['声压反射系数',a.r,''],['声压透射系数',a.t,''],['声强反射率',a.R*100,'%'],['声强透射率',a.T*100,'%']];}
case 'oblique':{const a=oblique(v);return [['折射角',a.angle,'°'],['临界角',a.critical,'°'],['法向功率反射率',a.R*100,'%'],['法向功率透射率',a.T*100,'%']];}
case 'standing':{const R=((v.R-1)**2+v.X*v.X)/((v.R+1)**2+v.X*v.X);return [['吸声率',(1-R)*100,'%'],['驻波比',(1+Math.sqrt(R))/(1-Math.sqrt(R)),'']];}
case 'spherical':return [['相对 1 m 扩展损失',20*Math.log10(v.r),'dB'],['kr',2*Math.PI*v.f*v.r/1500,'']];
case 'cylindrical':return [['相对 10 m 扩展损失',10*Math.log10(v.r/10),'dB']];
case 'image':{const r1=Math.hypot(100,10-v.depth),r2=Math.hypot(100,10+v.depth),k=2*Math.PI*v.f/1500;return [['100 m 水平距处相对直达幅值',Math.hypot(Math.cos(k*r1)/r1+v.sign*Math.cos(k*r2)/r2,Math.sin(k*r1)/r1+v.sign*Math.sin(k*r2)/r2)*r1,'']];}
case 'guide':{const fc=v.n*1500/(2*v.H),s=Math.sqrt(Math.max(0,1-(fc/v.f)**2));return [['截止频率',fc,'Hz'],['相速度',s>0?1500/s:NaN,'m/s'],['群速度',v.f>fc?1500*s:NaN,'m/s']];}
case 'monopole':return [['ka',ka,''],['归一化辐射阻',ka*ka/(1+ka*ka),''],['辐射声功率',.5*4*Math.PI*v.a*v.a*1500000*ka*ka/(1+ka*ka)*v.U*v.U,'W']];
case 'dipole':return [['kd',ka,''],['归一化幅值',Math.abs(Math.cos(v.angle*Math.PI/180)),'']];
case 'piston':return [['ka',ka,''],['观察方向归一化幅值',Math.abs(pistonD(ka*Math.sin(v.angle*Math.PI/180))),'']];
case 'nearfield':return [['瑞利距离估计',v.a*v.a*v.f/1500,'m'],['归一化轴向声压',2*Math.abs(Math.sin(Math.PI*v.f/1500*(Math.hypot(v.r,v.a)-v.r))),'']];
case 'scatter':return [['ka',ka,''],['总散射截面',7*Math.PI/9*v.a*v.a*ka**4,'m²']];
case 'cylinder':return [['边界总声压',0,'Pa'],['ka',v.ka,'']];
case 'receiver':return [['电压峰值',v.M/Math.hypot(1-v.ratio*v.ratio,2*v.z*v.ratio),'mV'],['归一化幅频响应',1/Math.hypot(1-v.ratio*v.ratio,2*v.z*v.ratio),'']];
case 'reciprocity':return [['A→B 归一化几何幅值',1/v.r,'m⁻¹'],['B→A 归一化几何幅值',1/v.r,'m⁻¹']];
case 'absorption':return [['声压剩余比例',100*Math.exp(-v.alpha*v.r),'%'],['吸收损失',20/Math.LN10*v.alpha*v.r,'dB']];
case 'mechanism':{const a=.001*(v.ratio**2+v.beta*v.ratio**2/(1+v.ratio**2));return [['模型吸收系数',a,'Np/m'],['100 m 吸收损失',20/Math.LN10*a*100,'dB']];}
case 'sonar':{const tl=20*Math.log10(v.r)+v.alpha*v.r/1000;return [['单程传播损失',tl,'dB'],['信号余量 SE',v.SL-2*tl+10-60+10-10,'dB']];}
default:return [];
}}
// Display precision only: calculations and shared parameter values remain unrounded.
export const fmt=(n:number)=>Number.isNaN(n)?'不适用':!Number.isFinite(n)?(n<0?'−∞':'∞'):n===0?'0.0':Math.abs(n)<.01||Math.abs(n)>=1000?n.toExponential(1):new Intl.NumberFormat('zh-CN',{minimumSignificantDigits:2,maximumSignificantDigits:2,useGrouping:false}).format(n);
