import {createContext,useContext,useState,type ReactNode} from 'react';
const TabsContext=createContext({value:'',onValueChange:(_s:string)=>{}});
export function Tabs({value,onValueChange,children}:{value:string,onValueChange:(s:string)=>void,children:ReactNode}){return <TabsContext.Provider value={{value,onValueChange}}>{children}</TabsContext.Provider>}
export function TabsList({children,className=''}:{children:ReactNode,className?:string}){return <div className={'native-tabs '+className} role="tablist">{children}</div>}
export function TabsTrigger({value,children}:{value:string,children:ReactNode}){const ctx=useContext(TabsContext);return <button role="tab" aria-selected={ctx.value===value} onClick={()=>ctx.onValueChange(value)}>{children}</button>}
export function TabsContent({value,children}:{value:string,children:ReactNode}){const ctx=useContext(TabsContext);return ctx.value===value?<section role="tabpanel">{children}</section>:null}
export function Slider({value,onValueChange,...props}:{value:number[],onValueChange:(n:number[])=>void,min:number,max:number,step:number,'aria-label':string}){return <input className="native-range" type="range" value={value[0]} {...props} onChange={e=>onValueChange([Number(e.target.value)])}/>}
export function SidebarProvider({children,className=''}:{children:ReactNode,className?:string}){return <div className={className}>{children}</div>}
export function Sidebar({children,className=''}:{children:ReactNode,className?:string,collapsible?:string}){return <aside className={className} aria-label="课程目录" tabIndex={0}>{children}</aside>}
export function SidebarContent({children}:{children:ReactNode}){return <div>{children}</div>}

export function NumericInput({value,min,max,step,onValueChange,...props}:{value:number;min:number;max:number;step:number;onValueChange:(n:number)=>void;id:string;'aria-label':string}){const [draft,setDraft]=useState(String(value)),[editing,setEditing]=useState(false);const snap=(n:number)=>Number(Math.min(max,Math.max(min,min+Math.round((n-min)/step)*step)).toFixed(9));function commit(){const n=Number(draft);if(draft.trim()!==''&&Number.isFinite(n))onValueChange(snap(n));setEditing(false)}return <input {...props} type="number" min={min} max={max} step={step} value={editing?draft:Number(value.toFixed(9))} onFocus={()=>{setDraft(String(Number(value.toFixed(9))));setEditing(true)}} onChange={e=>{const raw=e.target.value;setDraft(raw);setEditing(true);const n=Number(raw);if(raw.trim()!==''&&Number.isFinite(n)&&n>=min&&n<=max)onValueChange(snap(n))}} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter'){commit();e.currentTarget.blur()}if(e.key==='Escape'){setEditing(false);e.currentTarget.blur()}}}/>}
